import Link from "next/link";
import { requireTenantPermission } from "../../../lib/auth/authorization";
import { getAccessRoles, getTenantMembershipPermissions, getTenantMemberships, type TenantPermission } from "../../../lib/bcos-api";
import { assignUserRoleAction, inviteUserAction, removeUserAction, updateUserAction, updateUserPermissionsAction, updateUserStatusAction } from "./actions";

export const dynamic="force-dynamic";
const statusLabel={INVITED:"Convite pendente",ACTIVE:"Ativo",INACTIVE:"Bloqueado"} as const;
const groups:Array<{title:string;items:Array<{permission:TenantPermission;label:string}>}>=[
 {title:"Agenda",items:[["AGENDA_VIEW","Visualizar"],["AGENDA_CREATE","Criar"],["AGENDA_EDIT","Editar"],["AGENDA_DELETE","Excluir"],["AGENDA_MANAGE","Gerenciar"]].map(([permission,label])=>({permission:permission as TenantPermission,label}))},
 {title:"Disponibilidade e uso",items:[["AVAILABILITY_VIEW","Visualizar disponibilidade"],["CHECKIN_VIEW","Visualizar check-in e uso"],["CHECKIN_MANAGE","Gerenciar check-in e uso"]].map(([permission,label])=>({permission:permission as TenantPermission,label}))},
 {title:"Financeiro",items:[["FINANCE_VIEW","Visualizar"],["FINANCE_CREATE","Criar"],["FINANCE_EDIT","Editar"],["FINANCE_DELETE","Excluir"],["FINANCE_MANAGE","Gerenciar"]].map(([permission,label])=>({permission:permission as TenantPermission,label}))},
 {title:"Administração",items:[["ADMIN_VIEW","Visualizar"],["ADMIN_CONFIG","Editar configurações"],["USER_VIEW","Visualizar usuários"],["USER_CREATE","Criar/convidar usuário"],["USER_EDIT","Editar usuário"],["USER_BLOCK","Bloquear acesso"],["USER_DELETE","Remover acesso"],["ROLE_MANAGE","Gerenciar papel"],["USER_ADMIN","Gerenciar acessos"]].map(([permission,label])=>({permission:permission as TenantPermission,label}))},
 {title:"Outros",items:[{permission:"DASHBOARD_VIEW",label:"Visualizar visão geral"},{permission:"PROFESSIONAL_OWN",label:"Acessar o próprio portal profissional"}]},
];

export default async function UsersAdminPage({searchParams}:{searchParams:Promise<{invited?:string}>}){
 const actor=await requireTenantPermission("USER_VIEW");
 const [{invited},memberships,accessRoles]=await Promise.all([searchParams,getTenantMemberships(),getAccessRoles()]);
 const entries=await Promise.all(memberships.map(async item=>[item.id,await getTenantMembershipPermissions(item.id)] as const));
 const effective=new Map(entries);
 const activeRoles=accessRoles.filter(role=>role.active);
 const canCreate=actor.permissions.includes("USER_CREATE");
 const canManageRoles=actor.permissions.includes("ROLE_MANAGE");
 return <main className="admin-page admin-users-page">
  <header className="admin-page-head"><div><span>ADMINISTRAÇÃO / USUÁRIOS</span><h1>Usuários e acessos</h1><p>Cadastre a equipe, atribua os papéis criados pelo seu negócio e controle exceções individuais.</p></div><nav className="admin-section-nav" aria-label="Navegação da administração"><Link href="/administracao">← Configurações</Link>{canManageRoles?<Link href="/administracao/usuarios/papeis">Papéis e permissões</Link>:null}</nav></header>
  {invited?<div className="platform-success"><strong>Convite enviado</strong><span>O acesso ficará pendente até a pessoa aceitar o vínculo.</span></div>:null}
  <section className="tenant-user-summary"><div><strong>{memberships.length}</strong><span>Usuários</span></div><div><strong>{memberships.filter(x=>x.status==="ACTIVE").length}</strong><span>Ativos</span></div><div><strong>{memberships.filter(x=>x.status==="INACTIVE").length}</strong><span>Bloqueados</span></div></section>
  <section className="tenant-user-workspace"><section className="tenant-user-directory">
   <div className="tenant-section-title"><div><span>GESTÃO DE ACESSOS</span><h2>Equipe e acessos</h2><p>O proprietário administra usuários, papéis, permissões, bloqueios e remoções.</p></div></div>
   <div className="tenant-access-manager-status"><strong>Gerenciador de acessos do proprietário</strong><p>Os papéis são cadastrais e pertencem ao contratante. O papel define a base de acesso; exceções individuais podem ser ajustadas em cada usuário. O proprietário permanece protegido.</p></div>
   {memberships.filter(x=>x.role!=="OWNER").length===0?<div className="tenant-access-empty"><div><strong>Sua equipe ainda não possui outros usuários</strong><p>Use o painel “Convidar pessoa” para adicionar o primeiro integrante da equipe.</p></div></div>:null}
   <div className="tenant-user-list">{memberships.map(item=>{const owner=item.role==="OWNER";const granted=new Set(effective.get(item.id)??[]);const name=item.display_name||(owner?"Proprietário principal":"Usuário sem nome");const assigned=accessRoles.find(role=>role.id===item.access_role_id);
    return <article key={item.id} className="tenant-user-card tenant-user-card-professional"><div className="tenant-user-row"><div className="tenant-user-avatar">{name.slice(0,1).toUpperCase()}</div><div className="tenant-user-identity"><strong>{name}</strong><small>{item.email||"E-mail não informado"}</small></div><div className="tenant-user-meta"><span>{owner?"Proprietário":assigned?.name??"Sem papel cadastrado"}</span><span className={`tenant-user-status status-${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span></div><div className="tenant-user-row-actions">{owner?<span className="tenant-owner-lock">Acesso integral protegido</span>:<span>Gerenciar acesso ↓</span>}</div></div>
    {owner?<div className="tenant-owner-access"><strong>Proprietário do ambiente</strong><p>Possui acesso integral. Não pode ser rebaixado, bloqueado ou removido.</p></div>:<details className="tenant-user-editor tenant-user-editor-professional"><summary>Gerenciar acesso</summary><div className="tenant-access-console">
      <section className="tenant-access-panel"><div className="tenant-panel-head"><span>01</span><div><strong>Dados e papel</strong><small>Identidade e papel cadastrado do contratante.</small></div></div>
       <form className="tenant-user-edit-form tenant-user-edit-stacked" action={updateUserAction}><input type="hidden" name="membership_id" value={item.id}/><label>Nome<input name="display_name" defaultValue={item.display_name??""} required/></label><div className="tenant-user-readonly"><span>E-mail de acesso</span><strong>{item.email||"Não disponível"}</strong><small>Gerenciado pela conta de autenticação.</small></div><button type="submit">Salvar nome</button></form>
       <form className="tenant-user-edit-form tenant-user-edit-stacked" action={assignUserRoleAction}><input type="hidden" name="membership_id" value={item.id}/><label>Papel cadastrado<select name="access_role_id" defaultValue={item.access_role_id??""} required><option value="" disabled>Selecione</option>{activeRoles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><button type="submit" disabled={activeRoles.length===0}>Atribuir papel</button></form>
      </section>
      <section className="tenant-access-panel tenant-access-panel-wide"><div className="tenant-panel-head"><span>02</span><div><strong>Permissões individuais</strong><small>Exceções sobre a matriz do papel atribuído.</small></div></div><form className="tenant-permission-editor tenant-permission-matrix" action={updateUserPermissionsAction}><input type="hidden" name="membership_id" value={item.id}/>{groups.map(group=><fieldset key={group.title}><legend>{group.title}</legend>{group.items.map(entry=><label className="permission-check" key={entry.permission}><input type="checkbox" name={entry.permission} defaultChecked={granted.has(entry.permission)}/><span>{entry.label}</span></label>)}</fieldset>)}<button type="submit">Salvar permissões individuais</button></form></section>
      <section className="tenant-access-panel tenant-danger-panel"><div className="tenant-panel-head"><span>03</span><div><strong>Bloqueio e remoção</strong><small>Bloquear suspende a entrada; remover encerra somente o vínculo com este ambiente.</small></div></div><div className="tenant-user-access-actions"><form action={updateUserStatusAction}><input type="hidden" name="membership_id" value={item.id}/><input type="hidden" name="status" value={item.status==="ACTIVE"?"INACTIVE":"ACTIVE"}/><button type="submit">{item.status==="ACTIVE"?"Bloquear acesso":"Reativar acesso"}</button></form><form action={removeUserAction}><input type="hidden" name="membership_id" value={item.id}/><button className="danger" type="submit">Remover acesso</button></form></div></section>
    </div></details>}</article>})}</div>
  </section>
  <aside id="adicionar-usuario" className="tenant-invite-card tenant-invite-card-sticky"><span>NOVO ACESSO</span><h2>Convidar pessoa</h2><p>O convite exige um papel cadastrado pelo seu negócio.</p><form action={inviteUserAction}><label>Nome<input name="display_name" required placeholder="Nome completo"/></label><label>E-mail<input name="email" type="email" required placeholder="usuario@empresa.com"/></label><label>Papel<select name="access_role_id" defaultValue="" required><option value="" disabled>Selecione um papel</option>{activeRoles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><button type="submit" disabled={!canCreate||activeRoles.length===0}>Enviar convite de acesso</button></form><div className="tenant-password-policy"><strong>Senha protegida</strong><p>A senha pertence à conta de autenticação do próprio usuário e nunca é exibida nesta administração.</p></div></aside>
  </section>
 </main>;
}
