import Link from "next/link";

import { getTenantMemberships } from "../../../lib/bcos-api";
import { inviteUserAction, updateUserStatusAction } from "./actions";

export const dynamic="force-dynamic";
const roleLabel={OWNER:"Proprietário",ADMIN:"Administrador",RECEPTION:"Recepção",PROFESSIONAL:"Profissional"} as const;
const statusLabel={INVITED:"Convidado",ACTIVE:"Ativo",INACTIVE:"Inativo"} as const;

export default async function UsersAdminPage({searchParams}:{searchParams:Promise<{invited?:string}>}) {
  const [{invited},memberships]=await Promise.all([searchParams,getTenantMemberships()]);
  return <main className="tenant-admin-shell"><aside className="tenant-admin-rail"><div><div className="platform-brand"><span>C</span><div><strong>BCOS</strong><small>Administração do Coworking</small></div></div><nav><Link href="/administracao">Cadastros</Link><Link className="active" href="/administracao/usuarios">Usuários</Link></nav></div><div className="platform-rail-foot"><small>ÁREA DO CONTRATANTE</small><strong>Gestão do seu coworking</strong></div></aside><section className="platform-workspace"><header className="platform-header"><div><span>ADMINISTRAÇÃO / ACESSOS</span><strong>Usuários do coworking</strong></div><Link href="/">Ir para operação</Link></header><div className="platform-canvas">{invited?<div className="platform-success"><strong>Convite registrado</strong><span>O acesso permanece pendente até a identidade confiável ser ativada.</span></div>:null}<div className="platform-title"><span>EQUIPE E PROFISSIONAIS</span><h1>Quem pode acessar o BCOS.</h1><p>Administre os vínculos do seu coworking sem armazenar senhas no BCOS.</p></div><section className="tenant-user-layout"><div className="tenant-user-list">{memberships.map(item=><article key={item.id} className="tenant-user-card"><div><span>{roleLabel[item.role]}</span><strong>{item.external_user_id}</strong><small>{statusLabel[item.status]}</small></div>{item.role!=="OWNER"?<form action={updateUserStatusAction}><input type="hidden" name="membership_id" value={item.id}/><select name="status" defaultValue={item.status==="INVITED"?"ACTIVE":item.status}><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option></select><button type="submit">Atualizar</button></form>:<span className="tenant-owner-lock">OWNER</span>}</article>)}</div><aside className="tenant-invite-card"><span>NOVO ACESSO</span><h2>Convidar usuário</h2><p>Informe a identidade confiável e defina o papel. Convites não liberam acesso automaticamente.</p><form action={inviteUserAction}><label>Identidade externa<input name="external_user_id" required placeholder="ID da identidade confiável"/></label><label>Papel<select name="role" defaultValue="RECEPTION"><option value="ADMIN">Administrador</option><option value="RECEPTION">Recepção</option><option value="PROFESSIONAL">Profissional</option></select></label><button type="submit">Criar convite</button></form></aside></section></div></section></main>;
}
