import Link from "next/link";
import { requireTenantPermission } from "../../../../lib/auth/authorization";
import { getAccessRolePermissionCatalog, getAccessRoles } from "../../../../lib/bcos-api";
import { createRoleAction, deleteRoleAction, updateRoleAction } from "./actions";
export const dynamic="force-dynamic";

function Matrix({catalog,selected}:{catalog:Awaited<ReturnType<typeof getAccessRolePermissionCatalog>>;selected:Set<string>}){
 const modules=[...new Set(catalog.map(x=>x.module))];
 return <div className="tenant-role-matrix">{modules.map(module=><fieldset key={module}><legend>{module}</legend><div className="tenant-role-permission-grid">{catalog.filter(x=>x.module===module).map(item=><label className="permission-check" key={item.code}><input type="checkbox" name={"permission:"+item.code} defaultChecked={selected.has(item.code)}/><span>{item.action}</span></label>)}</div></fieldset>)}</div>;
}
export default async function RolesPage(){
 await requireTenantPermission("ROLE_MANAGE");
 const [roles,catalog]=await Promise.all([getAccessRoles(),getAccessRolePermissionCatalog()]);
 return <main className="admin-page admin-users-page">
  <header className="admin-page-head"><div><span>ADMINISTRAÇÃO / USUÁRIOS / PAPÉIS</span><h1>Papéis e permissões</h1><p>O contratante cria os papéis da própria operação e decide, por módulo e ação, o que cada papel pode executar.</p></div><nav className="admin-section-nav"><Link href="/administracao/usuarios">← Usuários e acessos</Link></nav></header>
  <section className="tenant-access-manager-status"><strong>Controle cadastral do contratante</strong><p>Nenhum papel de negócio é imposto pela HPTECH PLATFORM. O proprietário permanece a autoridade protegida; os demais papéis são criados, alterados, ativados e removidos pelo contratante.</p></section>
  <section className="tenant-user-workspace"><section className="tenant-user-directory"><div className="tenant-section-title"><div><span>PAPÉIS CADASTRADOS</span><h2>Matriz de acesso</h2><p>Marque Visualizar, Criar, Editar, Excluir, Bloquear, Gerenciar papel e Gerenciar acessos conforme a responsabilidade de cada papel.</p></div></div>
   <div className="tenant-user-list">{roles.length===0?<div className="tenant-access-empty"><strong>Nenhum papel cadastrado</strong><p>Crie o primeiro papel ao lado. Depois ele poderá ser atribuído aos usuários.</p></div>:roles.map(role=><details className="tenant-user-editor tenant-user-editor-professional" key={role.id}><summary>{role.name} · {role.assigned_users} usuário(s) · {role.active?"Ativo":"Inativo"}</summary><form className="tenant-access-console" action={updateRoleAction}><input type="hidden" name="role_id" value={role.id}/><section className="tenant-access-panel"><div className="tenant-panel-head"><span>01</span><div><strong>Identificação do papel</strong><small>Nome e finalidade definidos pelo contratante.</small></div></div><label>Nome<input name="name" defaultValue={role.name} required/></label><label>Descrição<textarea name="description" defaultValue={role.description??""}/></label><label className="permission-check"><input type="checkbox" name="active" defaultChecked={role.active}/><span>Papel ativo</span></label></section><section className="tenant-access-panel tenant-access-panel-wide"><div className="tenant-panel-head"><span>02</span><div><strong>Permissões do papel</strong><small>Autorizações efetivas para telas e ações.</small></div></div><Matrix catalog={catalog} selected={new Set(role.permissions)}/><button type="submit">Salvar papel e permissões</button></section><section className="tenant-access-panel tenant-danger-panel"><strong>Remoção segura</strong><p>Um papel com usuários vinculados não pode ser removido até que os acessos sejam reatribuídos.</p><button formAction={deleteRoleAction} className="danger" type="submit">Remover papel</button></section></form></details>)}</div>
  </section><aside className="tenant-invite-card tenant-invite-card-sticky"><span>NOVO PAPEL</span><h2>Cadastrar papel</h2><p>Crie um papel específico para a operação deste coworking.</p><form action={createRoleAction}><label>Nome<input name="name" required placeholder="Ex.: Gerente, Caixa, Recepção"/></label><label>Descrição<textarea name="description" placeholder="Responsabilidade deste papel"/></label><Matrix catalog={catalog} selected={new Set()}/><button type="submit">Cadastrar papel</button></form></aside></section>
 </main>;
}
