import Link from "next/link";
import { getPlatformOnboardingTerms } from "../../../lib/bcos-api";
import { publishPlatformTermsAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function PlatformTermsPage({ searchParams }: { searchParams: Promise<{ published?: string }> }) {
  const [terms, query] = await Promise.all([getPlatformOnboardingTerms(), searchParams]);
  return <main className="platform-shell"><aside className="platform-rail"><div><div className="platform-brand"><span>H</span><div><strong>HPTECH</strong><small>Administração BCOS</small></div></div><nav><Link href="/platform/clientes">Clientes</Link><Link href="/platform/clientes/novo">Novo cliente</Link><Link className="active" href="/platform/termos">Termos do profissional</Link></nav></div><div className="platform-rail-foot"><small>CONSOLE DA CONTRATADA</small><strong>HPTECH PLATFORM</strong></div></aside><section className="platform-workspace"><header className="platform-header"><div><span>HPTECH / GOVERNANÇA</span><strong>Termos do Portal do Profissional</strong></div></header><div className="platform-canvas">{query.published ? <div className="platform-success"><strong>Nova versão publicada.</strong><span>Os próximos cadastros profissionais receberão esta versão.</span></div> : null}<div className="platform-title"><span>AUTORIDADE DA PLATAFORMA</span><h1>Termos HPTECH PLATFORM / BCOS</h1><p>Este documento é global. O cliente contratante não pode alterá-lo.</p></div>{terms ? <section className="platform-detail-card"><span>VERSÃO VIGENTE</span><strong>{terms.title}</strong><p>Versão {terms.version} · vigente desde {new Date(terms.effective_at).toLocaleString("pt-BR")}</p><details><summary>Visualizar conteúdo vigente</summary><div className="document-preview">{terms.content}</div></details></section> : <section className="platform-notice"><strong>Nenhum termo vigente</strong><p>O autocadastro profissional permanece bloqueado até a primeira publicação.</p></section>}<section className="platform-detail-card"><span>PUBLICAR NOVA VERSÃO</span><form className="admin-form-grid" action={publishPlatformTermsAction}><label>Versão<input name="version" required placeholder="Ex.: 1.0"/></label><label>Título<input name="title" required placeholder="Termos de Uso do Portal do Profissional"/></label><label className="document-editor">Conteúdo<textarea name="content" required rows={18} placeholder="Cole aqui o texto jurídico aprovado."/></label><div className="admin-form-action"><button type="submit">Publicar nova versão</button></div></form><p>A publicação não altera aceites históricos. Uma nova versão passa a ser exigida somente nos novos cadastros.</p></section></div></section></main>;
}
